#!/usr/bin/env python3
#pip3 install adafruit-circuitpython-htu21d
import board
from adafruit_htu21d import HTU21D
import json

result = {}
try:
    # Create sensor object, communicating over the board's default I2C bus
    i2c = board.I2C()  # uses board.SCL and board.SDA
    sensor = HTU21D(i2c)
    result["temperature_c"] = sensor.temperature
    result["humidity"] = sensor.relative_humidity
    result["temperature_f"] = (result["temperature_c"]*1.8) + 32
    result["error"] = False
except:
    result["temperature_c"] = 0.0
    result["humidity"] = 0.0
    result["temperature_f"] = (result["temperature_c"]*1.8) + 32
    result["error"] = True

print(json.dumps(result))
